services:
  postgres:
    container_name: postgres-sql-lottery
    image: postgres
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: jug_lottery
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432

volumes:
  postgres:
    driver: local