spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jug_lottery
    driverClassName: org.postgresql.Driver
    username: login
    password: password
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true